const CONFIG={SUPABASE_URL:"https://rrogigeawlqhynzrppha.supabase.co",SUPABASE_ANON_KEY:"sb_publishable__Fiq-G_t1uk4YwyDacBOyQ_dhJnxdA1"};
let sb=null,user=null,mode="request",listings=[];
const $=id=>document.getElementById(id);
function ready(){return CONFIG.SUPABASE_URL.startsWith("https://")&&CONFIG.SUPABASE_ANON_KEY.length>20}
if(ready()){sb=supabase.createClient(CONFIG.SUPABASE_URL,CONFIG.SUPABASE_ANON_KEY);sb.auth.onAuthStateChange((_e,s)=>{user=s?.user||null;renderAuth();loadListings()});loadListings();}else{renderDemo()}
function renderAuth(){$("loginBtn").textContent=user?"Moje konto":"Zaloguj";$("authHint").textContent=user?`Zalogowany: ${user.email}`:"Zaloguj się, aby dodać ogłoszenie."}
function openModal(type){mode=type;$("listingType").value=type;$("modalTitle").textContent=type==="offer"?"🎟️ Mam kod":"🔎 Szukam kodu";$("storyLabel").firstChild.textContent=type==="offer"?"Informacje dla kibica":"Dlaczego chcesz być na meczu";$("modal").classList.remove("hidden")}
function renderDemo(){listings=[{type:"request",match:"Widzew — najbliższy mecz",sector:"dowolny",quantity:1,story:"Chcę zabrać syna na mecz. Jeśli ktoś ma niewykorzystany kod, będę bardzo wdzięczny."},{type:"request",match:"Widzew — mecz domowy",sector:"C",quantity:2,story:"Szukamy dwóch miejsc, żeby wspólnie pojawić się na stadionie."}];renderList()}
async function loadListings(){if(!sb)return;const {data,error}=await sb.from("listings").select("id,type,match,sector,quantity,story,created_at").eq("status","published").order("created_at",{ascending:false}).limit(50);if(!error){listings=data||[];renderList()}}
function renderList(){const f=$("typeFilter").value;const arr=listings.filter(x=>f==="all"||x.type===f);$("list").innerHTML=arr.length?arr.map(x=>`<article class="card"><span class="tag">${x.type==="offer"?"MAM KOD":"SZUKAM KODU"}</span><h3>${esc(x.match)}</h3><div class="muted">Sektor: ${esc(x.sector||"dowolny")} • ${x.quantity} kod</div><p>${esc(x.story)}</p><button class="help" onclick="contact('${x.id}')">❤️ Chcę pomóc</button></article>`).join(""):"<div class='empty'>Brak ogłoszeń.</div>"}
function esc(s){return String(s??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]))}
async function submitListing(e){e.preventDefault();if(!sb||!user)return alert("Najpierw skonfiguruj bazę i zaloguj się.");const payload={type:$("listingType").value,match:$("match").value.trim(),sector:$("sector").value.trim(),quantity:+$("quantity").value,story:$("story").value.trim(),user_id:user.id,status:"published"};const {error}=await sb.from("listings").insert(payload);if(error)return alert(error.message);$("modal").classList.add("hidden");e.target.reset();loadListings()}
async function contact(id){if(!user){$("auth").classList.remove("hidden");return}alert("W pełnej wersji połączymy Cię prywatnie z autorem ogłoszenia.")}
async function authSignup(){if(!sb)return alert("Najpierw wpisz dane Supabase w app.js.");const {error}=await sb.auth.signUp({email:$("email").value,password:$("password").value});alert(error?error.message:"Sprawdź e-mail, aby potwierdzić konto.")}
async function authSignin(){if(!sb)return alert("Najpierw wpisz dane Supabase w app.js.");const {error}=await sb.auth.signInWithPassword({email:$("email").value,password:$("password").value});if(error)alert(error.message);else $("auth").classList.add("hidden")}
$("typeFilter").onchange=renderList;$("close").onclick=()=>$("modal").classList.add("hidden");$("authClose").onclick=()=>$("auth").classList.add("hidden");$("loginBtn").onclick=()=>{$("auth").classList.remove("hidden");renderAuth()};document.querySelectorAll("[data-mode]").forEach(b=>b.onclick=()=>openModal(b.dataset.mode));$("listingForm").onsubmit=submitListing;$("signup").onclick=authSignup;$("signin").onclick=authSignin;$("logout").onclick=async()=>{if(sb)await sb.auth.signOut()};